#ifndef RALPH_CHARACTERS_H
#define RALPH_CHARACTERS_H
#include <Arduino.h>
const uint8_t RALPH_CHARS[8][8]={
{0b00000,0b01010,0b00000,0b00100,0b10001,0b01110,0b00000,0b00000},
{0b00000,0b00000,0b00000,0b00100,0b10001,0b01110,0b00000,0b00000},
{0b01010,0b01010,0b00000,0b00100,0b01110,0b01010,0b00000,0b00000},
{0b10001,0b01010,0b10001,0b00100,0b10001,0b01010,0b10001,0b00000},
{0b00100,0b01110,0b11111,0b10101,0b10101,0b10101,0b00000,0b00000},
{0b11111,0b10001,0b10101,0b10101,0b10001,0b11111,0b00000,0b00000},
{0b00000,0b00000,0b01010,0b00000,0b00100,0b01110,0b00000,0b00000},
{0b00000,0b00100,0b01110,0b11111,0b10101,0b11111,0b00000,0b00000}
};
static constexpr uint8_t RALPH_ANIMATION_COUNT=80;
const char* const RALPH_ANIMATIONS[80][3]={
{"Ralph           ","Ralph  ^        ","Ralph           "},
{"Ralph <         ","Ralph  <        ","Ralph           "},
{"Ralph       >   ","Ralph        >  ","Ralph           "},
{"Ralph ^_^       ","Ralph ^o^       ","Ralph ^_^       "},
{"Ralph >:(       ","Ralph -_-       ","Ralph >:(       "},
{"Ralph O_O       ","Ralph 0_0       ","Ralph O_O       "},
{"Ralph -_-       ","Ralph -.-       ","Ralph -_-       "},
{"Ralph -o-       ","Ralph  -        ","Ralph -o-       "},
{"Ralph hi        ","Ralph  hi       ","Ralph           "},
{"Ralph nod       ","Ralph  nod      ","Ralph           "},
{"Ralph no        ","Ralph NO        ","Ralph no        "},
{"   Ralph        ","    Ralph       ","     Ralph      "},
{"Ralph           ","                ","Ralph           "},
{"Ralph <         "," Ralph <        ","  Ralph <       "},
{"Ralph >         "," Ralph >        ","  Ralph >       "},
{"Ralph           ","Ralph           ","Ralph           "},
{"       Ralph    ","      Ralph     ","     Ralph      "},
{"    Ralph       ","   Ralph        ","  Ralph         "},
{"   Ralph        ","   Ralph  _     ","   Ralph        "},
{"   Ralph  |     ","   Ralph /      ","   Ralph  |     "},
{"Ralph   ^       "," Ralph ^        ","Ralph   ^       "},
{"Ralph   v       "," Ralph  v       ","Ralph   v       "},
{"Ralph /\        ","Ralph \ /       ","Ralph /\        "},
{"Ralph  o        ","Ralph   o       ","Ralph    o      "},
{"Ralph stretch   ","Ralph stretch   ","Ralph           "},
{"Ralph scratch   ","Ralph scratch   ","Ralph           "},
{"Ralph ...       ","Ralph ?         ","Ralph !         "},
{"Ralph ?         ","Ralph ??        ","Ralph ?         "},
{"Ralph !!!       ","Ralph ! !       ","Ralph !!!       "},
{"Ralph ...       ","Ralph ....      ","Ralph ...       "},
{"Ralph haha      ","Ralph heh       ","Ralph haha      "},
{"Ralph ;_;       ","Ralph :'(       ","Ralph ;_;       "},
{"Ralph >:(       ","Ralph >:(       ","Ralph >:(       "},
{"Ralph ._.       ","Ralph -_-       ","Ralph ._.       "},
{"Ralph B)        ","Ralph  B)       ","Ralph B)        "},
{"Ralph shy       "," Ralph shy      ","  Ralph shy     "},
{"Ralph O_O!      "," Ralph !        ","Ralph O_O!      "},
{"Ralph sus       ","Ralph SUS       ","Ralph sus       "},
{"Ralph zZz       ","Ralph Zzz       ","Ralph zZz       "},
{"Ralph waking    ","Ralph WAKING    ","Ralph awake     "},
{"Ralph down      ","Ralph o__       ","Ralph getting   "},
{"Ralph up        "," Ralph up       ","Ralph upright   "},
{"Ralph /         ","Ralph  /        ","Ralph  |        "},
{"Ralph \         ","Ralph  \        ","Ralph  |        "},
{"Ralph /         ","Ralph /         ","Ralph |         "},
{"Ralph \         ","Ralph  \        ","Ralph   |       "},
{"Ralph @_@       ","Ralph @.@       ","Ralph @_@       "},
{"Ralph  o        ","Ralph o         ","Ralph   o       "},
{"Ralph SHAKE     ","Ralph  SHAKE    ","Ralph SHAKE     "},
{"Ralph [ON]      ","Ralph [OFF]     ","Ralph [ON]      "},
{"   /\ House     ","   /\ House     ","   /\ House     "},
{"  /\House       "," /\ House       ","/\  House       "},
{"    House\      ","     House\     ","      House\    "},
{"   /\ [ ]       ","   /\ [ ]       ","   /\ [ ]       "},
{"   /\ [O]       ","   /\ [ ]       ","   /\ [O]       "},
{"   /\ []        ","   /\  []       ","   /\   []      "},
{"   /\ [ ]       ","   /\ [ ]       ","   /\ [ ]       "},
{"   /\House      ","  /\House       ","   /\House      "},
{"   /\ zZz       ","   /\ Zzz       ","   /\ zZz       "},
{"   /\ House     ","   /\ House     ","   /\ House     "},
{"   /\  ~        ","   /\ ~~        ","   /\ ~         "},
{"   /\  ^        ","   /\ ^^^       ","   /\  ^        "},
{"   /\  o        ","   /\           ","   /\  o        "},
{"   /\  /        ","   /\ |         ","   /\  \        "},
{"   /\  \        ","   /\ |         ","   /\  /        "},
{"   /\  *        ","   /\ ***       ","   /\  *        "},
{"   /\  ?        ","   /\  ?        ","   /\  ?        "},
{"Ralph []        ","Ralph [ ]       ","Ralph []        "},
{"Ralph [ ]       ","Ralph []        ","Ralph [ ]       "},
{"Ralph  OUT      ","Ralph   OUT     ","Ralph    OUT    "},
{"Ralph [door]    ","Ralph  [door]   ","Ralph [door]    "},
{"Ralph  HOUSE    ","Ralph HOUSE     ","Ralph  HOUSE    "},
{"Ralph outside   "," Ralph outside  ","  Ralph outside "},
{"Ralph /\        ","Ralph  /\       ","Ralph   /\      "},
{"Ralph [ ]       ","Ralph [O]       ","Ralph [ ]       "},
{"Ralph zZz /\    ","Ralph Zzz /\    ","Ralph zZz /\    "},
{"Ralph wakes!    ","Ralph  wakes!   ","Ralph awake!    "},
{"Ralph HI /\     ","Ralph hi /\     ","Ralph HI /\     "},
{"Ralph check     ","Ralph check /\  ","Ralph check     "},
{"Ralph fix /\    ","Ralph FIX /\    ","Ralph fixed!    "},
{"Ralph clean     ","Ralph clean /\  ","Ralph clean!    "},
{"Ralph relax     ","Ralph  relax    ","Ralph relax     "},
{"Ralph dance     ","Ralph /\ /\     ","Ralph dance     "},
{"Ralph jump /\   ","Ralph   ^ /\    ","Ralph land /\   "},
{"Ralph hide /\   ","   /\ Ralph     ","Ralph hide /\   "},
{"Ralph peek /\   ","Ralph /\ peek   ","Ralph peek /\   "},
{"Ralph mad /\    ","Ralph >:( /\    ","Ralph mad /\    "},
{"Ralph happy /\  ","Ralph ^_^ /\    ","Ralph happy /\  "},
{"Ralph tired /\  ","Ralph zZz /\    ","Ralph tired /\  "},
{"Ralph proud /\  ","Ralph B) /\     ","Ralph proud /\  "},
{"Ralph goodnight ","Ralph zZz /\    ","Ralph goodnight "},
{"Ralph morning / ","Ralph awake /\  ","Ralph morning / "}
};
const char* const RALPH_ANIMATION_NAMES[80]={
"blink","look_left","look_right","happy","grumpy","surprised","sleepy","yawn","wave","nod","shake_head","peek","hide","peek_left","peek_right","walk_left","walk_right","walk_home","sit","stand","hop","bounce","dance","wiggle","stretch","scratch","think","confused","excited","bored","laugh","cry","angry","calm","proud","shy","scared","suspicious","tired","wake_up","fall","recover","lean_left","lean_right","tilt_left","tilt_right","dizzy","spin","shake","brake","house_bob","house_left","house_right","door_open","door_close","window_left","window_right","roof_bounce","roof_wiggle","house_sleep","house_wake","house_shake","house_jump","house_land","house_tilt_left","house_tilt_right","house_flash","house_peek","ralph_at_door","ralph_inside","ralph_outside","ralph_roof","ralph_window","ralph_sleep_house","ralph_wakes_house","ralph_greets_house","ralph_checks_house","ralph_repairs","ralph_cleans","ralph_relaxes","ralph_dances_house","ralph_jumps_house","ralph_hides_house","ralph_peeks_house","ralph_mad_house","ralph_happy_house","ralph_tired_house","ralph_proud_house","ralph_goodnight_house","ralph_goodmorning_house"
};
#endif
